### ISSUE TITLE
Linux Machine : error: cannot find -lrt

### ISSUE THREAD

**Issue by akashgoyal** [KAlO2/PerfectShow#3]
Hi
I am working on a linux machine
Ran the 'ndk-build' on 'jni'. And stuck on below
/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: **error: cannot find -lrt**

Tried some variations in Android.mk like mentioned fullpath of 'librt'. But haven;t got it working.
Searched google all over but could not find anything.

Any suggestions on what probably could be missing / misplaced.

**Comment by KAlO2** [comment]
Sorry for late reply. I was on a vacation--Chinese New Year.
Now this is fixed in [6e4d4d0a35e59e109127d69a6a8f4d27564df58e](https://github.com/KAlO2/PerfectShow/commit/6e4d4d0a35e59e109127d69a6a8f4d27564df58e)

related problem: [Specify OpenMP to GCC](http://stackoverflow.com/questions/6351961/specify-openmp-to-gcc), -fopenmp flag implies -lgomp and -lrt, so I just replace -fopenmp with -lgomp.
